spring.data.mongodb.auto-index-creation=false


#Configuración refreshCookie 
app.cookie.http-only=true
app.cookie.secure=true
app.cookie.same-site=Lax

app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://manitas-crochet-frontend.onrender.com}


app.test-upload.enabled=false


#Control de mensaejes
logging.level.root=WARN
logging.level.com.manitascrochet=INFO