spring.data.mongodb.auto-index-creation=false


#Configuración refreshCookie 
app.cookie.http-only=true
app.cookie.secure=true
app.cookie.same-site=Lax

app.cors.allowed-origins=http://localhost:3000,http://192.168.0.16:3000
# produccion
#app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:https://www.manitascrochet.com}

app.test-upload.enabled=false


#Control de mensaejes
logging.level.root=WARN
logging.level.com.manitascrochet=INFO