spring.application.name=backend
# Url de conexión de MondoDb Altas
spring.data.mongodb.uri=${MONGODB_URI}
# Puerto de exposición de la APIs
server.port=${SERVER_PORT}
#configuracion subida de archivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# configuración token jwt
jwt.secret=${jwt.secret}
jwt.expirationMs=900000
jwt.refreshExpirationMs=604800000