spring.application.name=backend
# Url de conexión de MondoDb Altas
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true
# exposición de la APIs
app.protocolo=${APP_PROTOCOLO}
server.address=${SERVER_ADDRESS}
server.port=${SERVER_PORT}
# exposición de la frontend
app.frontend.url=${APP_FRONTEND_URL}
#configuracion subida de archivos
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
# configuración token jwt
jwt.secret=${jwt.secret}
jwt.expirationMs=900000
jwt.refreshExpirationMs=604800000
# configuración de correo electrónico Gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_ADDRESS}
spring.mail.password=${EMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Configuración refreshCookie 
app.cookie.http-only:true
app.cookie.secure:false
app.cookie.same-site:Lax

# Url del SecurityConfig
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:*}

# ImageKit
imagekit.public.key=${IMAGEKIT_PUBLIC_KEY}
imagekit.private.key=${IMAGEKIT_PRIVATE_KEY}
imagekit.url.endpoint=${IMAGEKIT_URL_ENDPOINT}
# Habilita el CommandLineRunner de prueba que sube imágenes de ejemplo a ImageKit al arrancar (solo para desarrollo/pruebas)
app.test-upload.enabled=false
